import { useState } from "react";

function BallotCard({ state, electionName, electionDate, selections }) {
  const formattedDate = new Date(electionDate + "T00:00:00").toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });

  return (
    <div id="ballot-card">
      <h2>I'm Voting in the {electionName}</h2>
      <p>{state} — {formattedDate}</p>
      <hr />
      {Object.entries(selections).map(([office, candidate]) => (
        <div key={office} style={{ marginBottom: "1rem" }}>
          <p style={{ margin: 0, fontWeight: "bold" }}>{office}</p>
          <p style={{ margin: 0 }}>{candidate}</p>
        </div>
      ))}
      <hr />
      <p>Generated by VoteAzul.com</p>
    </div>
  );
}

export default BallotCard;