import React from "react";
import html2canvas from "html2canvas";

function BallotCard({ state, electionName, electionDate, selections }) {
  const formattedDate = new Date(electionDate + "T00:00:00").toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });

  const handleDownload = () => {
    const card = document.getElementById("ballot-card");
    html2canvas(card).then((canvas) => {
      const link = document.createElement("a");
      link.download = "my-ballot.jpeg";
      link.href = canvas.toDataURL("image/jpeg", 0.9);
      link.click();
    });
  };

  return (
    <div>
      <div id="ballot-card">
        <h2>I'm Voting in the {electionName}</h2>
        <p>{state} — {formattedDate}</p>
        <hr />
        {Object.entries(selections).map(([office, candidate]) => (
          <div key={office} style={{ marginBottom: "1rem" }}>
            <p style={{ margin: 0, fontWeight: "bold" }}>{office}</p>
            <p style={{ margin: 0 }}>{candidate}</p>
          </div>
        ))}
        <hr />
        <p>Generated by VoteAzul.com</p>
      </div>
      <button onClick={handleDownload} style={{ marginTop: "1rem", fontSize: "1rem", padding: "0.5rem 1.5rem" }}>
        Download
      </button>
    </div>
  );
}

export default BallotCard;